"""add pipeline fields

Revision ID: 0fa3a7e7e5d4
Revises: 549f9c047084
Create Date: 2026-01-02 22:26:44.167465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fa3a7e7e5d4'
down_revision: Union[str, None] = '549f9c047084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('processing_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('data_sources', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('data_sources', sa.Column('quality_level', sa.String(length=20), nullable=True))
    op.add_column('data_sources', sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('data_sources', sa.Column('column_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('data_sources', sa.Column('cleaned_path', sa.Text(), nullable=True))
    op.add_column('data_sources', sa.Column('preview_path', sa.Text(), nullable=True))
    op.add_column('data_sources', sa.Column('processing_duration_seconds', sa.Float(), nullable=True))
    op.add_column('data_sources', sa.Column('last_processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'last_processed_at')
    op.drop_column('data_sources', 'processing_duration_seconds')
    op.drop_column('data_sources', 'preview_path')
    op.drop_column('data_sources', 'cleaned_path')
    op.drop_column('data_sources', 'column_stats')
    op.drop_column('data_sources', 'column_mapping')
    op.drop_column('data_sources', 'quality_level')
    op.drop_column('data_sources', 'quality_score')
    op.drop_column('data_sources', 'processing_report')
    # ### end Alembic commands ###
