"""Add DataSource, Query, and Visualization models

Revision ID: 605b244a5057
Revises: 3e8c96a3ad33
Create Date: 2025-12-03 06:53:13.490889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605b244a5057'
down_revision: Union[str, None] = '3e8c96a3ad33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
